//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLExport1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://schemas.datacontract.org/2004/07/GetDataLib")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RobotNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeFrameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string srvHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int srvPortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Login {
            get {
                return this.LoginField;
            }
            set {
                if ((this.LoginField.Equals(value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaPath {
            get {
                return this.MetaPathField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaPathField, value) != true)) {
                    this.MetaPathField = value;
                    this.RaisePropertyChanged("MetaPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RobotName {
            get {
                return this.RobotNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RobotNameField, value) != true)) {
                    this.RobotNameField = value;
                    this.RaisePropertyChanged("RobotName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeFrame {
            get {
                return this.TimeFrameField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeFrameField, value) != true)) {
                    this.TimeFrameField = value;
                    this.RaisePropertyChanged("TimeFrame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string srvHost {
            get {
                return this.srvHostField;
            }
            set {
                if ((object.ReferenceEquals(this.srvHostField, value) != true)) {
                    this.srvHostField = value;
                    this.RaisePropertyChanged("srvHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int srvPort {
            get {
                return this.srvPortField;
            }
            set {
                if ((this.srvPortField.Equals(value) != true)) {
                    this.srvPortField = value;
                    this.RaisePropertyChanged("srvPort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.IGetData")]
    public interface IGetData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAddressFileSRV", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAddressFileSRVResponse")]
        void GetAddressFileSRV(DLLExport1.ServiceReference1.ClientInfo _Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAddressFileSRV", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAddressFileSRVResponse")]
        System.Threading.Tasks.Task GetAddressFileSRVAsync(DLLExport1.ServiceReference1.ClientInfo _Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountNum", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountNumResponse")]
        void GetAccountNum(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountNum", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountNumResponse")]
        System.Threading.Tasks.Task GetAccountNumAsync(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetPassword", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetPasswordResponse")]
        void GetPassword(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetPassword", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetPasswordResponse")]
        System.Threading.Tasks.Task GetPasswordAsync(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetStatuseRUN", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetStatuseRUNResponse")]
        void GetStatuseRUN(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetStatuseRUN", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetStatuseRUNResponse")]
        System.Threading.Tasks.Task GetStatuseRUNAsync(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountType", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountTypeResponse")]
        void GetAccountType(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountType", ReplyAction="http://Microsoft.ServiceModel.Samples/IGetData/GetAccountTypeResponse")]
        System.Threading.Tasks.Task GetAccountTypeAsync(string Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataChannel : DLLExport1.ServiceReference1.IGetData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataClient : System.ServiceModel.ClientBase<DLLExport1.ServiceReference1.IGetData>, DLLExport1.ServiceReference1.IGetData {
        
        public GetDataClient() {
        }
        
        public GetDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetAddressFileSRV(DLLExport1.ServiceReference1.ClientInfo _Value) {
            base.Channel.GetAddressFileSRV(_Value);
        }
        
        public System.Threading.Tasks.Task GetAddressFileSRVAsync(DLLExport1.ServiceReference1.ClientInfo _Value) {
            return base.Channel.GetAddressFileSRVAsync(_Value);
        }
        
        public void GetAccountNum(string Value) {
            base.Channel.GetAccountNum(Value);
        }
        
        public System.Threading.Tasks.Task GetAccountNumAsync(string Value) {
            return base.Channel.GetAccountNumAsync(Value);
        }
        
        public void GetPassword(string Value) {
            base.Channel.GetPassword(Value);
        }
        
        public System.Threading.Tasks.Task GetPasswordAsync(string Value) {
            return base.Channel.GetPasswordAsync(Value);
        }
        
        public void GetStatuseRUN(string Value) {
            base.Channel.GetStatuseRUN(Value);
        }
        
        public System.Threading.Tasks.Task GetStatuseRUNAsync(string Value) {
            return base.Channel.GetStatuseRUNAsync(Value);
        }
        
        public void GetAccountType(string Value) {
            base.Channel.GetAccountType(Value);
        }
        
        public System.Threading.Tasks.Task GetAccountTypeAsync(string Value) {
            return base.Channel.GetAccountTypeAsync(Value);
        }
    }
}
